In [1]:
import numpy as np
import pandas as pd

In [3]:
ds = pd.read_csv("data.csv")

In [15]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        837 non-null    object
 1   company     837 non-null    object
 2   year        837 non-null    object
 3   Price       837 non-null    object
 4   kms_driven  837 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 45.8+ KB


In [23]:
ds["year"].unique()

array([2007, 2006, 2018, 2014, 2015, 2012, 2013, 2016, 2010, 2017, 2008,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001],
      dtype=int64)

In [35]:
ds.dropna(inplace = True)

In [19]:
ds["year"] = pd.to_numeric(ds["year"], errors='coerce')

In [39]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        816 non-null    object 
 1   company     816 non-null    object 
 2   year        816 non-null    int64  
 3   Price       816 non-null    float64
 4   kms_driven  816 non-null    object 
 5   fuel_type   816 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 44.6+ KB


In [27]:
ds["Price"] = ds["Price"].str.replace(",", "")

In [31]:
ds["Price"] = pd.to_numeric(ds["Price"], errors='coerce')

In [37]:
ds["Price"].unique()

array([  80000.,  425000.,  325000.,  575000.,  175000.,  190000.,
        830000.,  250000.,  182000.,  315000.,  415000.,  320000.,
       1000000.,  500000.,  350000.,  160000.,  310000.,   75000.,
        100000.,  290000.,   95000.,  180000.,  385000.,  105000.,
        650000.,  689999.,  448000.,  549000.,  501000.,  489999.,
        280000.,  349999.,  284999.,  345000.,  499999.,  235000.,
        249999., 1475000.,  395000.,  220000.,  170000.,   85000.,
        200000.,  570000.,  110000.,  448999., 1891111.,  159500.,
        344999.,  449999.,  865000.,  699000.,  375000.,  224999.,
       1200000.,  195000.,  351000.,  240000.,   90000.,  155000.,
        600000.,  189500.,  210000.,  390000.,  135000., 1600000.,
        701000.,  265000.,  525000.,  372000.,  635000.,  550000.,
        485000.,  329500.,  251111.,  569999.,   69999.,  299999.,
        399999.,  450000.,  270000.,  158400.,  179000.,  125000.,
        299000.,  150000.,  285000.,  340000.,   70000.,  2899

In [43]:
ds["kms_driven"] = ds["kms_driven"].str.replace(",", "").str.replace(" kms", "")

In [47]:
ds["kms_driven"] = pd.to_numeric(ds["kms_driven"], errors='coerce')

In [57]:
ds = ds[ds["kms_driven"] >= 10000]

In [61]:
ds = ds[ds["kms_driven"] <= 200000]

In [69]:
ds["fuel_type"].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [73]:
ds["company"].unique()

array(['Hyundai', 'Ford', 'Maruti', 'Skoda', 'Mahindra', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Mercedes', 'Land', 'Force', 'Jaguar', 'Volvo'], dtype=object)

In [83]:
for i in ds.index:
    company = ds.loc[i, "company"]
    name = ds.loc[i, "name"]
    name = name.replace(company, "").strip()
    ds.loc[i, "name"] = name

In [99]:
ds.duplicated().unique()

array([False])

In [97]:
ds.drop_duplicates(inplace = True)

In [101]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 651 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        651 non-null    object 
 1   company     651 non-null    object 
 2   year        651 non-null    int64  
 3   Price       651 non-null    float64
 4   kms_driven  651 non-null    int64  
 5   fuel_type   651 non-null    object 
dtypes: float64(1), int64(2), object(3)
memory usage: 35.6+ KB


In [109]:
ds[["company", "name", "year", "kms_driven", "fuel_type", "Price"]].to_csv("cleaned_data.csv")

In [107]:
ds.reset_index(inplace = True)